# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: inteldev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: trusstai
# "service" is the name of this project. This will also be added to your AWS resource names.
service: trusst-ai-challenge

stages:
  default:
    params:
      tableName: "call-intents-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource:
            - Fn::GetAtt: [CallIntentsTable, Arn]
  timeout: 30
  environment:
    CALL_INTENTS_TABLE: ${param:tableName}

functions:
  clusterCallIntentsScheduled:
    handler: handler.clusterCallIntentsScheduled
    events:
      - schedule: rate(1 minute)  # The Lambda will run once a minute
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-finch

resources:
  Resources:
    CallIntentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: call_id
            AttributeType: S
        KeySchema:
          - AttributeName: call_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}

custom:
  client:
    bucketName: trusst-ai-client