# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: inteldev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: trusstai
# "service" is the name of this project. This will also be added to your AWS resource names.
service: trusst-ai-challenge

stages:
  default:
    params:
      tableName: "call-intents-2-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource:
            - Fn::GetAtt: [CallIntentsTable, Arn]
        - Effect: Allow
          Action:
            - es:ESHttpGet
            - es:ESHttpPost
            - es:ESHttpPut
          Resource: arn:aws:es:us-east-1:509399592131:domain/trusstai/*
  environment:
    CALL_INTENTS_TABLE: ${param:tableName}
    OPEN_SEARCH_ENDPOINT: "https://search-trusstai-3d2u3v6ktzotnzhmaj3bycumte.us-east-1.es.amazonaws.com"
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

functions:
  clusterCallIntentsScheduled:
    handler: handler.clusterCallIntentsScheduled
    events:
      - schedule: rate(1 minute)  # The Lambda will run once a minute
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
        cors: true

plugins:
  - serverless-offline
  - serverless-finch

resources:
  Resources:
    CallIntentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: call_id
            AttributeType: S
        KeySchema:
          - AttributeName: call_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}

custom:
  client:
    bucketName: trusst-ai-client